import { Header } from "./header/componentes";
import { CarrosInfo } from "./section/componentes";
import {Footer} from "./footer/componentes";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({}: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh", 
          }}
        >
          <Header subtopico="Stênio Éric Barrêto da Costa" />
          <main style={{ flex: 1 }}>
            <CarrosInfo />
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
